SELECT AVG(m.y) OVER(
    ORDER BY m.audio_time ROWS BETWEEN 1102 PRECEDING AND CURRENT ROW) 
    -- ORDER BY m.audio_time ROWS BETWEEN 1102 PRECEDING AND CURRENT ROW) 
    AS avg_y
FROM maestro AS m
